[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
PROPACK = "b169e327-5944-5131-97a6-5d3d3f0a476a"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
CSV = "0.8"
DataFrames = "0.22"
DynamicPolynomials = "0.3"
FiniteDifferences = "0.12"
ForwardDiff = "0.10"
JuMP = "0.21"
MultivariatePolynomials = "0.3"
ReverseDiff = "1.7"
ZipFile = "0.9"
